### ISSUE TITLE
Design tweaks

### ISSUE THREAD

**Issue by kfrn** [steviekaye/budget-tracker#13]
Here's a potential alteration of the navbar:

![bt_navbar-desktop](https://user-images.githubusercontent.com/16832997/52173484-5564a300-27ea-11e9-9e47-7640e141a66a.png)

NB: this doesn't use the font-awesome icon - I made it with a span containing a regular text dollar sign. Then styled with `border-radius`, height & width, margin and padding, etc.

Now that I look again, the dollar sign and its circle are probably a bit too big, though.  
If you prefer to keep the icon as-is - please still enlarge the size of the name.

**Comment by kfrn** [comment]
Categories page:
![bt_categories](https://user-images.githubusercontent.com/16832997/52173529-361a4580-27eb-11e9-90f7-39efe6a9dd8e.png)

* Spacing of page name (global change for all `h1`s)
* More clearly visually group category + subcategories by decreasing the spacing between the category & its subcategories, and also adding more space after each group of subcategories

**Comment by kfrn** [comment]
Summaries page:

![bt_summaries](https://user-images.githubusercontent.com/16832997/52173616-91990300-27ec-11e9-9378-68bbbe304cfe.png)

* Add headings for charts
* Spacing (NB, the ring chart could have slightly more whitespace after than in the screenshot)

**Comment by kfrn** [comment]
* The Purchases page basically looks good
* New Purchase - have some whitespace between the nav and the form card.

NB: All of the above just shows the desktop views. Check that mobile also looks good! It might need different spacings/etc.

**Comment by steviekaye** [comment]
Good suggestions - I've implemented them in the latest build.
